package fr.harmoniamk.statsmk.enums

import fr.harmoniamk.statsmk.R

enum class Cups(
    val label: Int,
    val picture: Int,
    val isRetro: Boolean = false,
    val isDLC: Boolean = false
) {
    MUSHROOM(R.string.mushroom, R.drawable.mushroom),
    FLOWER(R.string.flower, R.drawable.flower),
    STAR(R.string.star, R.drawable.star),
    SPECIAL(R.string.special, R.drawable.special),
    EGG(R.string.egg, R.drawable.egg, isDLC = true),
    TRIFORCE(R.string.triforce, R.drawable.triforce, isDLC = true),
    SHELL(R.string.shell, R.drawable.shell, isRetro = true),
    BANANA(R.string.banana, R.drawable.banana, isRetro = true),
    LEAF(R.string.leaf, R.drawable.leaf, isRetro = true),
    LIGHTNING(R.string.lightning, R.drawable.lightning, isDLC = true),
    CROSSING(R.string.crossing, R.drawable.crossing, isDLC = true),
    BELL(R.string.bell, R.drawable.bell, isDLC = true),
}

enum class Maps(val label: Int, val picture: Int, val cup: Cups) {
    MKS(R.string.mks, R.drawable.mks, Cups.MUSHROOM),
    WP(R.string.wp, R.drawable.wp, Cups.MUSHROOM),
    SSC(R.string.ssc, R.drawable.ssc, Cups.MUSHROOM),
    TR(R.string.tr, R.drawable.tr, Cups.MUSHROOM),
    MC(R.string.mc, R.drawable.mc, Cups.FLOWER),
    TH(R.string.th, R.drawable.th, Cups.FLOWER),
    TM(R.string.tm, R.drawable.tm, Cups.FLOWER),
    SGF(R.string.sgf, R.drawable.sgf, Cups.FLOWER),
    SA(R.string.sa, R.drawable.sa, Cups.STAR),
    DS(R.string.ds, R.drawable.ds, Cups.STAR),
    Ed(R.string.ed, R.drawable.ed, Cups.STAR),
    MW(R.string.mw, R.drawable.mw, Cups.STAR),
    CC(R.string.cc, R.drawable.cc, Cups.SPECIAL),
    BDD(R.string.bdd, R.drawable.bdd, Cups.SPECIAL),
    BC(R.string.bc, R.drawable.bc, Cups.SPECIAL),
    RR(R.string.rr, R.drawable.rr, Cups.SPECIAL),
    dYC(R.string.dyc, R.drawable.dyc, Cups.EGG),
    dEA(R.string.dea, R.drawable.dea, Cups.EGG),
    dDD(R.string.ddd, R.drawable.ddd, Cups.EGG),
    dMC(R.string.dmc, R.drawable.dmc, Cups.EGG),
    dWGM(R.string.dwgm, R.drawable.dwgm, Cups.TRIFORCE),
    dRR(R.string.drr, R.drawable.drr, Cups.TRIFORCE),
    dIIO(R.string.diio, R.drawable.diio, Cups.TRIFORCE),
    dHC(R.string.dhc, R.drawable.dhc, Cups.TRIFORCE),
    rMMM(R.string.rmmm, R.drawable.rmmm, Cups.SHELL),
    rMC(R.string.rmc, R.drawable.rmc, Cups.SHELL),
    rCCB(R.string.rccb, R.drawable.rccb, Cups.SHELL),
    rTT(R.string.rtt, R.drawable.rtt, Cups.SHELL),
    rDDD(R.string.rddd, R.drawable.rddd, Cups.BANANA),
    rDP3(R.string.rdp3, R.drawable.rdp3, Cups.BANANA),
    rRRy(R.string.rrry, R.drawable.rrry, Cups.BANANA),
    rDKJ(R.string.rdkj, R.drawable.rdkj, Cups.BANANA),
    rWS(R.string.rws, R.drawable.rws, Cups.LEAF),
    rSL(R.string.rsl, R.drawable.rsl, Cups.LEAF),
    rMP(R.string.rmp, R.drawable.rmp, Cups.LEAF),
    rYV(R.string.ryv, R.drawable.ryv, Cups.LEAF),
    rTTC(R.string.rttc, R.drawable.rttc, Cups.LIGHTNING),
    rPPS(R.string.rpps, R.drawable.rpps, Cups.LIGHTNING),
    rGV(R.string.rgv, R.drawable.rgv, Cups.LIGHTNING),
    rRRd(R.string.rrrd, R.drawable.rrrd, Cups.LIGHTNING),
    dBP(R.string.dbp, R.drawable.dbp, Cups.CROSSING),
    dCL(R.string.dcl, R.drawable.dcl, Cups.CROSSING),
    dWW(R.string.dww, R.drawable.dww, Cups.CROSSING),
    dAC(R.string.dac, R.drawable.dac, Cups.CROSSING),
    dNBC(R.string.dnbc, R.drawable.dnbc, Cups.BELL),
    dRiR(R.string.drir, R.drawable.drir, Cups.BELL),
    dSBS(R.string.dsbs, R.drawable.dsbs, Cups.BELL),
    dBB(R.string.dbb, R.drawable.dbb, Cups.BELL),
}